### ISSUE TITLE
WHERE ARE THE DATASET?

### ISSUE THREAD

**Issue by zy486at189cn** [scheidan/DeePrecip#1]
First ,it is a great job!
I want to realize the project, but I have no dataset . Can you tell me where can I download the train dataset and the test dataset? Thank!

**Comment by scheidan** [comment]
The data where provided by [MeteoSwiss](http://www.meteoswiss.admin.ch/home.html?tab=overview). Unfortunately, I'm not allowed to share them.

Some radar date for Germany are available here: [ftp://ftp-cdc.dwd.de/pub/CDC/](ftp://ftp-cdc.dwd.de/pub/CDC/) . However, I never had a closer look at them.
